routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
// use Yajra\DataTables\Contracts\DataTable;
use yajra\DataTables\DataTables;
// use  App\Http\Controllers\InstallggpmController;
// use GuzzleHttp\Client;

// $client = new Client([
//     //url de base con la que se hace la peticion
//             'base_uri' => 'https://10.2.36.179/api/',
//             //tiempo de espera para conectar a la api
//             'timeout'  => 5.0,
//             ]
// );
// $response = $client->request('POST', "clientes?national_id=V011111111", ['verify' => false]);
// // dd(json_decode($response->getBody()->getContents()));
// // $respon=json_decode($response->getBody()->getContents('clie_id'));
// // $respon = compact($response);
// // dd( $respon);
// $respon = explode(' ', $response->getBody()->getContents());
// // $respon->getBody()->getContents();
// // for ($i=0; $i > 5 ; $i++) {
// //     # code...
// //     dd($respon[$i]);
// // }
// // $otro = explode(',', $respon->count());
// dd($respon);
// // dd($response->getBody()->getContents());




// dd($response->getBody()->getContents());

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });



Route::get('/', function () {
    // return view('auth.login');
    return view('auth.login');
});
Route::get('/welcome', function () {
    // return view('auth.login');
    return view('auth.register');
});

// Route::get('aprovicion', 'Auth\aprovicionController@index');
// Route::post('aprovicion', 'Auth\aprovicionController@store')->name('aprovicion');
Route::get('/relacionFlujos', function () {
    // return view('auth.login');
    return view('relacionFlujos.relacionFlujos');
});
Route::prefix('/')->group(function () {
    Route::resource('Opeinternas', 'CotiController')->name('CotiController@index', 'Opeinternas');
});
Route::prefix('/')->group(function () {
    Route::resource('ggto','GgtoController')->name('GgtoController@index', 'ggto');
    Route::get('/ggtos','GgtoController@all');
});
Route::post('/comic', function () {
    // $contents = SSH::run(['mkdir /dcantv/directorio12',
    //     ]);
    return request()->all();
});

Route::get('/elementoRed', function () {
    // return view('auth.login');
    return view('elementoRed.elementoRed');
});
Route::get('/elementoDetalle', function () {
    // return view('auth.login');
    return view('elementoDetalle.elementoDetalle');
});
Route::get('/servicio', function () {
    // return view('auth.login');
    return view('servicios.servicio');
});
Route::prefix('proveedor')->group(function () {
    Route::resource('/', 'ProveedorController')->name('ProveedorController@index', 'proveedor');
    Route::get('/', 'ProveedorController@show');
    Route::get('/all', 'ProveedorController@all')->name('proveedors');
});

Route::prefix('/')->group(function () {
    Route::resource('central', 'CentralController')->name('CentralController@index', 'central'); //api
    Route::get('/centrals', 'CentralController@mostrar');
});
Route::prefix('/')->group(function () {
    Route::resource('aprovision', OltController::class)->names('aprovision');
    Route::get('/tipos','OltController@optionTipo');
    // Route::resource('aprovision', 'OltController')->name('OltController@index','aprovision');
    Route::get('/aprovisions', 'OltController@mostrar');
    // Route::get('/aprovisiones', 'OltController@mostrar2');
});
Route::prefix('/')->group(function () {
    Route::resource('TargetPort', TargetPortController::class)->name('TargetPortController@index','TargetPort');
    Route::get('/TargetPorts', 'TargetPortController@mostrar');
});
Route::prefix('/')->group(function () {
    Route::resource('ont', 'OntController')->name('OntController@index', 'ont');
    Route::get('/onts', 'OntController@mostrar');
});







Route::prefix('/')->group(function () {
    Route::resource('product', 'ProductController')->name('ProductController@index', 'product'); // api
    Route::get('/products', 'ProductController@mostrar');
});
Route::prefix('/')->group(function () {
    Route::resource('service', ServiceProfileController::class)->names('service');
    // Route::resource('service', 'ServiceProfileController')->name('ServiceProfileController@index','service');
    Route::get('/services', 'ServiceProfileController@mostrar');
});
Route::prefix('/')->group(function () {
    Route::resource('online', OnlineProfileController::class)->names('online');
    // Route::resource('online', 'OnlineProfileController')->name('OnlineProfileController@index','online');
    Route::get('/onlines', 'OnlineProfileController@mostrar');
});
Route::prefix('/')->group(function () {
    Route::resource('planes', 'PlanController')->name('PlanController@all', 'planes'); //api
    Route::get('/plans', 'PlanController@mostrar');
});








Route::prefix('/')->group(function () {
    Route::resource('sfp', SfpController::class)->name('SfpController@index', 'sfp'); //api
    Route::get('/sfps', 'SfpController@mostrar');

});
Route::prefix('/')->group(function () {
    Route::resource('tipo', 'TipoController')->name('TipoController@index', 'tipo'); //api

});








Route::prefix('/')->group(function () {
    Route::resource('ordenes', OrdenController::class)->name('OrdenController@index', 'ordenes'); // agregar campos cedula y numero de servicio
    Route::get('ordenes/all', 'OrdenController@all');
    Route::get('detalles','OrdenController@detalles');
    Route::post('detalles/save','OrdenController@save');
 });
// Route::resource('ordenes', 'OrdenController')->name('OrdenController@index', 'ordenes');






Route::resource('install', 'InstallController')->name('InstallController@index','install');
// Route::resource('sales', 'SaleController')->name('SaleController@index','sales');
Route::resource('config', 'ConfiguraController')->name('ConfiguraController@index', 'config')->middleware('permission:config.index');
// Route::resource('ZonaSale', 'ZonaSaleController')->name('ZonaSaleController@store', 'ZonaSale');
// Route::post('ZonaSale', 'ZonaSaleController@store')->name('ZonaSale');






Route::get('/installs', 'InstallController@mostrar');



Route::post('/apiProduct', 'ApiOrdenController@store');



Route::get('ciudades', 'SaleController@getCiudad');
Route::get('/central/{{}}/ciudadesedit', 'SaleController@getCiudad');
Route::get('municipios', 'SaleController@getMunicipio');
Route::get('parroquias', 'SaleController@getParroquia');
Route::get('urbanizaciones', 'SaleController@getUrbanizacion');
Route::get('sfpt', 'SfpController@mostrar');
Route::get('sfpgp', 'SfpController@mostrargpon');
Route::get('sfptup', 'SfpController@mostrarup');




Route::get('oltodos', 'InstallggpmController@getOlt');
Route::get('odftodos', 'InstallggpmController@getOdf');
Route::get('tartodos', 'InstallggpmController@getTarget');
Route::get('porttodos', 'InstallggpmController@getPort');

// Route::get('/centrals', function () {
//     // return view('auth.login');
//     return  datatables::of(App\central::query())->make(true);
// });

// Route::get('puertos', 'Auth\aprovicionController@index2')->name('cards_ports');
// Route::post('puertos', 'Auth\aprovicionController@store2');

// Route::get('linea', 'Auth\aprovicionController@index3')->name('online_profile');
// Route::post('linea','Auth\aprovicionController@store3');

// Route::get('registrar', 'Auth\aprovicionController@index4')->name('install');
// Route::post('registrar', 'Auth\aprovicionController@store4');

// Route::get('ventas', 'Auth\aprovicionController@index5')->name('sales');
// Route::post('ventas', 'Auth\aprovicionController@store5');

// Route::get('servicios', 'Auth\aprovicionController@index6')->name('service_profile');
// Route::post('servicios', 'Auth\aprovicionController@store6');

/* Route::get('datos', 'Auth\aprovicionController@index7')->name('datos');
Route::post('datos', 'Auth\aprovicionController@store7'); */

// Route::Post('datos', 'Auth\LoginController@login')->name('login');

Auth::routes();
Route::prefix('/')->group(function () {


Route::resource('Installggpm', InstallggpmController::class)->names('installggpm');
});
Route::get('/installggpms', 'InstallggpmController@mostrar');

Route::prefix('/')->group(function () {
    Route::resource('Odf', OdfController::class)->names('Odf');
    Route::get('/odfs', 'OdfController@mostrar');
    Route::get('/odf1', 'OdfController@mostrar1');



   });

// Route::get('/home', 'CentralController@show')->name('home');
Route::get('/home', function () {
    return view('home');
});

Route::prefix('/')->group(function () {
    Route::resource('config_card', config_cardController::class)->names('config_card');
    Route::get('/config_cards', 'config_cardController@mostrar');

});

Route::prefix('/')->group(function () {
    Route::resource('manga', MangaController::class)->names('manga');
    Route::get('/mangas', 'MangaController@mostrar');
    Route::get('/mangas1', 'MangaController@mostrar2');
    Route::get('/mangas2', 'MangaController@mostrar3');


});

Route::prefix('/')->group(function () {
    Route::resource('splitter', SplitterController::class)->names('splitter');
    Route::get('/splitters', 'SplitterController@mostrar');
    Route::get('/splitter1', 'SplitterController@mostrar3');
    Route::get('/splitter2', 'SplitterController@mostrar2');



});

/*------------------------SERVICIOS SOAP----------------------------------*/

Route::get('/CrearNuevoSuscriptorAba','CrearNuevoSuscriptorController@store');

app/Odf.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Odf extends Model
{
    //
}

app/Http/Controllers/OdfController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Auth;
use yajra\DataTables\DataTables;

use App\central;
use App\Odf;


use Illuminate\Http\Request;

class OdfController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $central = central::get();
        // $odf = Odf::get();

        $fijo = "Fibra Central";
        return view('odf.odf',compact('central','fijo'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'central'=>'required',
            'odf'=>'required|string',
            'sala'=>'required|string|between:2,25',
            'piso'=>'required|string|between:2,4',
            'bastidor'=>'required|string|between:2,4',
            'frame'=>'required|string|between:2,4',
            'bandeja'=>'required|string|between:2,4',
            'posicion'=>'required|string',
            'tipo_cable'=>'required',
            'capacidad'=>'required|string|between:2,25',
            'distancia'=>'required|string|between:2,25',
            'ruta'=>'required|string|between:2,25',
        ]);

        // $odf = Odf::create($request->all());
        
        Odf::insert([

            'central' => $request->central,
            'odf' => $request->odf,
            'sala' => $request->sala,
            'piso' => $request->piso,
            'bastidor' => $request->bastidor,
            'frame' => $request->frame,
            'bandeja' => $request->bandeja,
            'posicion' => $request->posicion,
            'tipo_cable' => $request->tipo_cable,
            'capacidad' => $request->capacidad,
            'ruta' => $request->ruta,
            'distancia' => $request->distancia,
            'created_at' => now()->toDateTime(),
            'user_email_created' => Auth::user()->email,
        ]);
// modificado por jorge "msg" => "Estimado usuario, el odf". $request->odf." se ha creado exitosamente",
        $respuesta['respuesta'] = array(
            "title" => "Creación de central",
            "msg" => "Estimado usuario, el odf se ha creado exitosamente",
            "ruta" => "Odf",
            "otros" => ""
        );

        return view('mensajes.satisfactorio', $respuesta);

        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id_odf)
    {
        //
        $odf=Odf::findOrFail($id_odf);
        
        $central=Central::findOrFail($odf->central);
        
        return view('odf.edit',['odf'=>$odf,'central'=>$central]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_odf)
    {
        //
        $odf = $request->except(['_token', '_method']);
        $request->validate([
           
            'odf'=>'required|string',
            'sala'=>'required|string|between:2,25',
            'piso'=>'required|string|between:2,4',
            'bastidor'=>'required|string|between:2,4',
            'frame'=>'required|string|between:2,4',
            'bandeja'=>'required|string|between:2,4',
            'posicion'=>'required|string',
            'tipo_cable'=>'required',
            'capacidad'=>'required|string|between:2,25',
            'distancia'=>'required|string|between:2,25',
            'ruta'=>'required|string|between:2,25',
        ]);

        
        try {
            Odf::where('id', '=', $id_odf)->update([

                
                'odf' => $request->odf,
                'sala' => $request->sala,
                'piso' => $request->piso,
                'bastidor' => $request->bastidor,
                'frame' => $request->frame,
                'bandeja' => $request->bandeja,
                'posicion' => $request->posicion,
                'tipo_cable' => $request->tipo_cable,
                'capacidad' => $request->capacidad,
                'ruta' => $request->ruta,
                'distancia' => $request->distancia,
                'created_at' => now()->toDateTime(),
                'user_email_created' => Auth::user()->email,
            ]);
            $respuesta['respuesta'] = array(
                "title" => "Modificación de ODF",
                "msg" => "Estimado usuario, el ODF se ha modificado exitosamente",
                "ruta" => "Odf",
                "otros" => ""
            );
            return view('mensajes.satisfactorio', $respuesta);
        } catch (\Throwable $th) {
            //throw $th;
            $respuesta['respuesta'] = array(
                "title" => "Creación de ODF",
                "msg" => "Estimado usuario, no se ha podido realizar la modificación del ODF, intente más tarde.",
                "ruta" => 'Odf',
                "otros" => ""
            );
            return view('mensajes.error', $respuesta);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    // public function mostrar2()
    // {
    //     //
    //     $datos['odf'] = Odf::paginate(5);
    //     // return view('service_Profile.index', $datos);
    //     return view('aprovicion.form', $datos);
    // }

    public function mostrar()
    {
        //
        $respuesta = Odf::paginate(5);
        return view('odf.form',['odfs'=>$respuesta]);
    }

    public function mostrar1()
    {
        //
        $respuesta = Odf::select('*')
        ->get();
        return $respuesta;
    }
}

resources/views/odf/edit.blade.php
@extends('layouts.app')

@section('content')
@inject('estados', 'App\Services\estados')

<body class="container">

    <div class="main-container container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-xl-12">
                <form id="centalForm" name="form" method="post" class="form-horizontal" action="{{url('/Odf/'.$odf->id)}}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('PATCH')}}
                    <div id="formulario_registro">

                        <!-- datos personales-->

                        <div class='col-xs-12 col-sm-12 col-md-12 col-xl-12'>
                            <h3 class="gris"><strong> ODF </strong></h3>
                            <hr />
                            <p class="label-inf">Completa todos los campos del formulario con los datos solicitados.</p>
                            <hr />

                        </div>


                        <div class="aside">
                            @include('layouts.menu_left')

                        </div>


                        <div class='col-xs-8 col-sm-8 col-md-8 col-xl-8 col-xs-offset-1 col-md-offset-1 col-sm-offset-1'>

                            <div class='class="col-xs-12"'>
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="#">Aprovisionamiento</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">ODF</li>
                                    </ol>
                                </nav>
                            </div>
                           
                            <div class="form-group col-xs-12">
                                <label class="control-label col-xs-6 required" for="form_codigo_central">Central <label class="rojo">*</label></label>
                                <div class=''>
                                    <div class='col-xs-6'>
                                        <input type="text" name="central" class="form-control tip" readonly placeholder="{{$central->name_central}}">
                                        {!! $errors->first('central','<span class="alert-danger fade in">:message</span>')!!}
                                    </div>
                                </div>
                            </div>

                            <div class="form-group col-xs-12">
                                <label class="control-label col-xs-6 required" for="form_codigo_central">ODF <label class="rojo">*</label></label>
                                <div class=''>
                                    <div class='col-xs-6'>
                                        <input type="text" id="odf" name="odf"  value="{{$odf->odf}}" class="form-control tip" maxlength="50"  title="Ingresa el número sin puntos" />

                                        {!! $errors->first('odf','<span class="alert-danger fade in">:message</span>')!!}
                                    </div>
                                </div>
                            </div>

                            <div class="form-group col-xs-12">
                                <label class="control-label col-xs-6 required" for="form_codigo_central">Sala <label class="rojo">*</label></label>
                                <div class=''>
                                    <div class='col-xs-6'>
                                        <input type="text" id="sala" name="sala"  value="{{$odf->sala}}" class="form-control tip" maxlength="50"  title="Ingresa el número sin puntos" />

                                        {!! $errors->first('sala','<span class="alert-danger fade in">:message</span>')!!}
                                    </div>
                                </div>
                            </div>

                          <div class="form-group col-xs-12">
                                <label class="control-label col-xs-6 required" for="form_codigo_central">Piso <label class="rojo">*</label></label>
                                <div class=''>
                                    <div class='col-xs-6'>
                                        <input type="text" id="piso" name="piso"  value="{{$odf->piso}}" class="form-control tip" maxlength="50"  title="Ingresa el número sin puntos" />

                                        {!! $errors->first('piso','<span class="alert-danger fade in">:message</span>')!!}
                                    </div>
                                </div>
                            </div>

                            <div class="form-group col-xs-12">
                                <label class="control-label col-xs-6 required" for="form_codigo_central">Bastidor <label class="rojo">*</label></label>
                                <div class=''>
                                    <div class='col-xs-6'>
                                        <input type="text" id="bastidor" name="bastidor"  value="{{$odf->bastidor}}" class="form-control tip" maxlength="50"  title="Ingresa el número sin puntos" />

                                        {!! $errors->first('bastidor','<span class="alert-danger fade in">:message</span>')!!}
                                    </div>
                                </div>
                            </div>

                            <div class="form-group col-xs-12">
                                <label class="control-label col-xs-6 required" for="form_codigo_central">Frame <label class="rojo">*</label></label>
                                <div class=''>
                                    <div class='col-xs-6'>
                                        <input type="text" id="frame" name="frame"  value="{{$odf->frame}}" class="form-control tip" maxlength="50"  title="Ingresa el número sin puntos" />

                                        {!! $errors->first('frame','<span class="alert-danger fade in">:message</span>')!!}
                                    </div>
                                </div>
                            </div>

                            <div class="form-group col-xs-12">
                                <label class="control-label col-xs-6 required" for="form_codigo_central">Bandeja <label class="rojo">*</label></label>
                                <div class=''>
                                    <div class='col-xs-6'>
                                        <input type="text" id="bandeja" name="bandeja"  value="{{$odf->bandeja}}" class="form-control tip" maxlength="50"  title="Ingresa el número sin puntos" />

                                        {!! $errors->first('bandeja','<span class="alert-danger fade in">:message</span>')!!}
                                    </div>
                                </div>
                            </div>

                            <div class="form-group col-xs-12">
                                <label class="control-label col-xs-6 required" for="form_codigo_central">Posición <label class="rojo">*</label></label>
                                <div class=''>
                                    <div class='col-xs-6'>
                                        <input type="text" id="posicion" name="posicion"  value="{{$odf->posicion}}" class="form-control tip" maxlength="50"  title="Ingresa el número sin puntos" />

                                        {!! $errors->first('posicion','<span class="alert-danger fade in">:message</span>')!!}
                                    </div>
                                </div>
                            </div>


                            <div class='col-xs-12 col-sm-12 col-md-12 col-xl-12'>
                                <hr />
                            </div>
                             <div class='col-xs-12 col-sm-12 col-md-12 col-xl-12'>
                                <label class="control-label col-xs-4 required" for="form_cedula">
                                    <h5 class="gris"><strong> Cable</strong></h5>
                                </label>
                            </div>
                            <div class="form-group col-xs-12">
                                <label class="control-label col-xs-6 required" for="form_codigo_central">Tipo de cable <label class="rojo">*</label></label>
                                <div class=''>
                                    <div class='col-xs-6'>
                                        <input type="text" id="tipo_cable" name="tipo_cable" value ="Fibra central"  protected readonly placeholder="" class="form-control tip" maxlength="50"  title="Ingresa el número sin puntos" />

                                        {!! $errors->first('tipo_cable','<span class="alert-danger fade in">:message</span>')!!}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-xs-12">
                                <label class="control-label col-xs-6 required" for="form_codigo_central">Capacidad <label class="rojo">*</label></label>
                                <div class=''>
                                    <div class='col-xs-6'>
                                        <input type="text" id="capacidad" name="capacidad"  value="{{$odf->capacidad}}" class="form-control tip" maxlength="50"  title="Ingresa el número sin puntos" />

                                        {!! $errors->first('capacidad','<span class="alert-danger fade in">:message</span>')!!}
                                    </div>
                                </div>
                            </div>

                            <div class="form-group col-xs-12">
                                <label class="control-label col-xs-6 required" for="form_codigo_central">Distancía <label class="rojo">*</label></label>
                                <div class=''>
                                    <div class='col-xs-6'>
                                        <input type="text" id="distancia" name="distancia"  value="{{$odf->distancia}}" class="form-control tip" maxlength="50"  title="Ingresa el número sin puntos" />

                                        {!! $errors->first('distancia','<span class="alert-danger fade in">:message</span>')!!}
                                    </div>
                                </div>
                            </div>

                            <div class="form-group col-xs-12">
                                <label class="control-label col-xs-6 required" for="form_codigo_central">Ruta <label class="rojo">*</label></label>
                                <div class=''>
                                    <div class='col-xs-6'>
                                        <input type="text" id="ruta" name="ruta"  value="{{$odf->ruta}}" class="form-control tip" maxlength="50"  title="Ingresa el número sin puntos" />

                                        {!! $errors->first('posicion','<span class="alert-danger fade in">:message</span>')!!}
                                    </div>
                                </div>
                            </div>
                       </div>
                        <div class='col-xs-12 col-sm-12 col-md-12 col-xl-12'>
                            <hr />
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-xl-4  form-group">
                            <p>(*)Campo obligatorio.</p>
                            <div class="form-group  pull-right">
                                <button type="submit" class="btn btn-primary" onClick="">Editar</button>
                                <a href="{{ url('/odfs') }}">
                                    <button type="button" class="btn btn-primary" onClick="">Mostrar Todos</button>
                                </a>

                            </div>
                        </div>
                    </div>
                    <!-- fin de la primera parte del formulario-->
                </form>
            </div>
        </div>
    </div>
</body>
@endsection

resources/views/odf/form.blade.php
@extends('layouts.app')

@section('content')

<body class="container">

    <div class="main-container container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-xl-12">
                {{ csrf_field() }}
                <!-- datos personales-->
                <div class='col-xs-12 col-sm-12 col-md-12 col-xl-12'>
                    <!-- <span class="badge pull-right numero_formulario_registro">1</span> -->
                    <h3 class="gris"><strong> ODF </strong></h3>
                    <hr />
                    <!-- <p class="label-inf">Completa todos los campos del formulario con los datos solicitados.</p> -->
                    <!-- <hr /> -->
                </div>
                <div class="aside">
                    @include('layouts.menu_left')
                </div>
                <div class='col-xs-8 col-sm-8 col-md-8 col-xl-8 col-xs-offset-1 col-md-offset-1 col-sm-offset-1'>
                    <div class="panel-body table-responsive" id="listadoregistros">
                             <div class='class="col-xs-12"'>
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="#">Aprovisionamiento</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">ODF</li>
                                    </ol>
                                </nav>
                            </div>
                        <table id="tbllistado" class="table table-striped table-bordered table-condensed table-hover">
                            <thead>
                                <th>#</th>
                                <th>ODF</th>
                                <th>Sala</th>
                                <th>piso</th>
                                <th>Opciones</th>
                            </thead>
                            <tbody>
                                @foreach($odfs as $odf)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{ $odf->odf}}</td>
                                    <td>{{ $odf->sala}}</td>
                                    <td>{{ $odf->piso}}</td>
                                    
                                    <td>
                                        <a href="{{ route('Odf.edit',$odf->id)}}">
                                            <button class="btn btn-warning" onclick="">Editar<i class="fa fa-pencil"></i></button>
                                        </a>
                                    </td>
                                    
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
    </div>
</body>
@endsection